/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cyberhub;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import cyberhub.Conexiones;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;

/**
 *
 * @author duran
 */
public class añadir extends javax.swing.JFrame {

    /**
     * Creates new form añadir
     */
    public añadir() {
        initComponents();
        contarID();
    }
    
    public void contarID(){
        try { 
                Conexiones.con = Conexiones.crear();
                
                String sqlCount = "SELECT COUNT(*) FROM videojuegos";
                Statement stmt = Conexiones.con.createStatement();
                ResultSet rs = stmt.executeQuery(sqlCount);
                rs.next();
                int rowCount = rs.getInt(1);
                rs.close();
                stmt.close();

                int nextId = rowCount + 1;
                id_juego.setText(String.valueOf(nextId));
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al obtener la ID.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pl2 = new javax.swing.JComboBox<>();
        pl3 = new javax.swing.JComboBox<>();
        pl4 = new javax.swing.JComboBox<>();
        pl5 = new javax.swing.JComboBox<>();
        pl6 = new javax.swing.JComboBox<>();
        pl1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        lanzamientoTexto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        desarrolladoraTexto = new javax.swing.JTextField();
        id_juego = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tituloTexto = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        formatos = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel22.setText("Título");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel21.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel21.setText("Lanzamiento");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel20.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel20.setText("Formato");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel19.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel19.setText("Plataformas");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        jLabel23.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel23.setText("Descripción");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel24.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel24.setText("ID");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, -1, 40));

        pl2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null", "Dreamcast", "Game Boy", "Game Boy Advance", "Game Boy Color", "GameCube", "Master System", "Mega Drive", "NES", "Nintendo 3DS", "Nintendo 64", "Nintendo DS", "Nintendo Switch", "PlayStation", "PlayStation 2", "PlayStation 3", "PlayStation 4", "PlayStation 5", "PSP", "PS Vita", "Sega Saturn", "SNES", "Wii", "Wii U", "Xbox", "Xbox 360", "Xbox One", "Xbox Series X/S" }));
        jPanel1.add(pl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 289, 29));

        pl3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null", "Dreamcast", "Game Boy", "Game Boy Advance", "Game Boy Color", "GameCube", "Master System", "Mega Drive", "NES", "Nintendo 3DS", "Nintendo 64", "Nintendo DS", "Nintendo Switch", "PlayStation", "PlayStation 2", "PlayStation 3", "PlayStation 4", "PlayStation 5", "PSP", "PS Vita", "Sega Saturn", "SNES", "Wii", "Wii U", "Xbox", "Xbox 360", "Xbox One", "Xbox Series X/S" }));
        jPanel1.add(pl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 289, 29));

        pl4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null", "Dreamcast", "Game Boy", "Game Boy Advance", "Game Boy Color", "GameCube", "Master System", "Mega Drive", "NES", "Nintendo 3DS", "Nintendo 64", "Nintendo DS", "Nintendo Switch", "PlayStation", "PlayStation 2", "PlayStation 3", "PlayStation 4", "PlayStation 5", "PSP", "PS Vita", "Sega Saturn", "SNES", "Wii", "Wii U", "Xbox", "Xbox 360", "Xbox One", "Xbox Series X/S" }));
        jPanel1.add(pl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 289, 29));

        pl5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null", "Dreamcast", "Game Boy", "Game Boy Advance", "Game Boy Color", "GameCube", "Master System", "Mega Drive", "NES", "Nintendo 3DS", "Nintendo 64", "Nintendo DS", "Nintendo Switch", "PlayStation", "PlayStation 2", "PlayStation 3", "PlayStation 4", "PlayStation 5", "PSP", "PS Vita", "Sega Saturn", "SNES", "Wii", "Wii U", "Xbox", "Xbox 360", "Xbox One", "Xbox Series X/S" }));
        jPanel1.add(pl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 289, 29));

        pl6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null", "Dreamcast", "Game Boy", "Game Boy Advance", "Game Boy Color", "GameCube", "Master System", "Mega Drive", "NES", "Nintendo 3DS", "Nintendo 64", "Nintendo DS", "Nintendo Switch", "PlayStation", "PlayStation 2", "PlayStation 3", "PlayStation 4", "PlayStation 5", "PSP", "PS Vita", "Sega Saturn", "SNES", "Wii", "Wii U", "Xbox", "Xbox 360", "Xbox One", "Xbox Series X/S" }));
        jPanel1.add(pl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 289, 29));

        pl1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null", "Dreamcast", "Game Boy", "Game Boy Advance", "Game Boy Color", "GameCube", "Master System", "Mega Drive", "NES", "Nintendo 3DS", "Nintendo 64", "Nintendo DS", "Nintendo Switch", "PlayStation", "PlayStation 2", "PlayStation 3", "PlayStation 4", "PlayStation 5", "PSP", "PS Vita", "Sega Saturn", "SNES", "Wii", "Wii U", "Xbox", "Xbox 360", "Xbox One", "Xbox Series X/S" }));
        jPanel1.add(pl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 289, 29));

        jButton1.setText("Cargar Imagen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, -1, -1));

        lanzamientoTexto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lanzamientoTexto.setBorder(null);
        jPanel1.add(lanzamientoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 289, 29));

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 620, 280));

        desarrolladoraTexto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        desarrolladoraTexto.setBorder(null);
        jPanel1.add(desarrolladoraTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 289, 29));

        id_juego.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        id_juego.setBorder(null);
        jPanel1.add(id_juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 170, 29));

        jLabel25.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel25.setText("Carátula");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, 40));

        tituloTexto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tituloTexto.setBorder(null);
        jPanel1.add(tituloTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 289, 29));

        jLabel26.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel26.setText("Desarrolladora");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        formatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Físico", "Digital", "Físico/Digital" }));
        jPanel1.add(formatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 289, 29));

        jPanel2.setBackground(new java.awt.Color(255, 102, 255));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AÑADIR");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos JPG", "jpg"));

        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            String id = id_juego.getText();
            
            Path directorioDestino = Paths.get("src\\cyberhub\\imagenes\\");
            if (!Files.exists(directorioDestino)) {
                try {
                    Files.createDirectories(directorioDestino);
                } catch (IOException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Error al crear el directorio.");
                    return;
                }
            }
            
            Path rutaDestino = directorioDestino.resolve(id + ".jpg");

            try {
                Files.copy(archivoSeleccionado.toPath(), rutaDestino);
                JOptionPane.showMessageDialog(this, "Imagen guardada.");
            } catch (IOException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al guardar la imagen.");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String nombre = tituloTexto.getText();
        String id = id_juego.getText();
        String lanzamientoStr = lanzamientoTexto.getText();
        String desarrolladora = desarrolladoraTexto.getText();
        String formato = (String) formatos.getSelectedItem();
        String p1 = (String) pl1.getSelectedItem();
        String p2 = (String) pl2.getSelectedItem();
        String p3 = (String) pl3.getSelectedItem();
        String p4 = (String) pl4.getSelectedItem();
        String p5 = (String) pl5.getSelectedItem();
        String p6 = (String) pl6.getSelectedItem();
        String descripcion = desc.getText();
        
        int lanzamiento = 0;
        try {
            lanzamiento = Integer.parseInt(lanzamientoStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El lanzamiento debe ser un número entero.");
            return;
        }
        
        String plataformas = "";
        if (p1 != null && !p1.equals("null")) plataformas += p1 + ", ";
        if (p2 != null && !p2.equals("null")) plataformas += p2 + ", ";
        if (p3 != null && !p3.equals("null")) plataformas += p3 + ", ";
        if (p4 != null && !p4.equals("null")) plataformas += p4 + ", ";
        if (p5 != null && !p5.equals("null")) plataformas += p5 + ", ";
        if (p6 != null && !p6.equals("null")) plataformas += p6;
        
        if (!plataformas.isEmpty()) {
            plataformas = plataformas.substring(0, plataformas.length() - 2);
        }

        try {
            Conexiones.con = Conexiones.crear();
            
            String sqlInsertVideojuego = "INSERT INTO videojuegos (nombre, id, anio, desarrolladora, formato, plataformas) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement psInsertVideojuego = Conexiones.con.prepareStatement(sqlInsertVideojuego);
            psInsertVideojuego.setString(1, nombre);
            psInsertVideojuego.setString(2, id);
            psInsertVideojuego.setInt(3, lanzamiento);
            psInsertVideojuego.setString(4, desarrolladora);
            psInsertVideojuego.setString(5, formato);
            psInsertVideojuego.setString(6, plataformas);
            psInsertVideojuego.executeUpdate();
            psInsertVideojuego.close();
            
            String sqlInsertInformacion = "INSERT INTO informacion (id_juego, descripcion, P1, P2, P3, P4, P5, P6) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement psInsertInformacion = Conexiones.con.prepareStatement(sqlInsertInformacion);
            psInsertInformacion.setString(1, id);
            psInsertInformacion.setString(2, descripcion);
            psInsertInformacion.setString(3, p1);
            psInsertInformacion.setString(4, p2);
            psInsertInformacion.setString(5, p3);
            psInsertInformacion.setString(6, p4);
            psInsertInformacion.setString(7, p5);
            psInsertInformacion.setString(8, p6);
            psInsertInformacion.executeUpdate();
            psInsertInformacion.close();

            JOptionPane.showMessageDialog(this, "Registros insertados.");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al insertar.");
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new añadir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField desarrolladoraTexto;
    private javax.swing.JTextArea desc;
    private javax.swing.JComboBox<String> formatos;
    private javax.swing.JTextField id_juego;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lanzamientoTexto;
    private javax.swing.JComboBox<String> pl1;
    private javax.swing.JComboBox<String> pl2;
    private javax.swing.JComboBox<String> pl3;
    private javax.swing.JComboBox<String> pl4;
    private javax.swing.JComboBox<String> pl5;
    private javax.swing.JComboBox<String> pl6;
    private javax.swing.JTextField tituloTexto;
    // End of variables declaration//GEN-END:variables
}
