/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cyberhub;

import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import cyberhub.Conexiones;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author duran
 */
public class tendencia extends javax.swing.JFrame {

    /**
     * Creates new form tendencia
     */
    public tendencia() {
        initComponents();
        Conexiones.crear();
        //actualizarTable(Conexiones.con);
        cargarFoto(Conexiones.con);
    }
    
    /*public void actualizarTable(Connection con) {
    DefaultTableModel tm = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    tm.addColumn("Nombre");
    tm.addColumn("ID");
    tm.addColumn("Me Gustas");
    jTable1.setModel(tm);

    try {
        String sql = "SELECT v.nombre, v.id, COUNT(c.aniadido) AS me_gustas "
                   + "FROM videojuegos v "
                   + "LEFT JOIN comentario c ON v.id = c.id_del_juego AND c.aniadido = TRUE "
                   + "GROUP BY v.nombre, v.id "
                   + "ORDER BY me_gustas DESC "
                   + "LIMIT 10";
        System.out.println(sql);
        Statement lee = con.createStatement();
        ResultSet resultado = lee.executeQuery(sql);

        while (resultado.next()) {
            Object[] datos = new Object[3];
            datos[0] = resultado.getString("nombre");
            datos[1] = resultado.getString("id");
            datos[2] = resultado.getInt("me_gustas");

            tm.addRow(datos);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}*/
    public void cargarFoto(Connection con) {
    try {
        String sql = "SELECT v.id "
                   + "FROM videojuegos v "
                   + "LEFT JOIN comentario c ON v.id = c.id_del_juego AND c.aniadido = TRUE "
                   + "GROUP BY v.id "
                   + "ORDER BY COUNT(c.aniadido) DESC "
                   + "LIMIT 1";
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery(sql);

        String idJuegoMasGustado = null;
        if (rs.next()) {
            idJuegoMasGustado = rs.getString("id");
        }

        if (idJuegoMasGustado != null) {
            Image imagenOriginal = ImageIO.read(getClass().getResource("\\imagenes\\" + idJuegoMasGustado + ".jpg"));
            Image imagenEscalada = imagenOriginal.getScaledInstance(300, 400, Image.SCALE_SMOOTH);

            ImageIcon imagenIcono = new ImageIcon(imagenEscalada);
            jLabel1.setIcon(imagenIcono);

            jLabel1.revalidate();
            jLabel1.repaint();
        } else {
            System.out.println("No se encontró el juego más gustado.");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tendencias");
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tendencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tendencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tendencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tendencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tendencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
